### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by sj817** [NotThorny/AttackModifier#1]
Hello, how do I compile it, I have tried many methods, and they all suggest that it cannot be compiled.

**Comment by NotThorny** [comment]
You can get maven if you don't already have it, then open a cmd to your AttackModifier root and run `mvn package` which will build the jar to the `\target` folder.

For building in your IDE of choice, this does use a grasscutter-1.3.1.jar as a dependency, and you can get that from the Grasscutter github releases page. You'll want to put that jar into your Maven dependencies folder.

**Comment by sj817** [comment]
Solved, thanks!
