### ISSUE TITLE
3.4 Not working

### ISSUE THREAD

**Issue by keqingyyds** [NotThorny/AttackModifier#14]
The command works normally, there is no error prompt, and the role has no effect. Use the docker jar

**Comment by NotThorny** [comment]
I've built it on 3.4 docker and tested it, should be good to go with this jar. The releases will be updated when normal GC updates as well.
[Docker-AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10667824/Docker-AttackModifier.zip)

**Comment by keqing114514** [comment]
> I've built it on 3.4 docker and tested it, should be good to go with this jar. The releases will be updated when normal GC updates as well. [Docker-AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10667824/Docker-AttackModifier.zip)

3.4 new config error
