### ISSUE TITLE
More help with commands

### ISSUE THREAD

**Issue by MrCheese2431** [NotThorny/AttackModifier#17]
There is little to no tutorials in the readme on how to use the plugin. Could you add an example command or a list of ids we can use? The only things in the readme are the basic commands. What even is a gadget in this situation? I would like to get some help with this if that's possible.

**Comment by NotThorny** [comment]
The basic commands are the only usage, there's no special stuff.
`/at set n 42906105`
`/at set q 42906105`
`/at off`
`/at on`

Gadgets are literally gadget items from the game. You can find gadget ids either from Grasscutter resources, in GadgetExcelConfigData.json, or from YuukiPS's GM Handbook where the ids are included.

Fair note that not every gadget works, some work but are hard to see or go in weird angles and may not be visible easily. You'll have to try out gadgets and find ones you like.

**Comment by NotThorny** [comment]
If you'd rather not dig through the resources yourself, you can also find a list of gadget ids on Jie's commandgenerator github: https://github.com/jie65535/GrasscutterCommandGenerator/blob/main/Source/GrasscutterTools/Resources/en-us/Gadget.txt

As the file hasn't been updated in 8 months, it won't include new gadgets from newer game versions, so I'd still recommend using YuukiPS's GM Handbook for an updated list that doesn't need you to be looking through resources. 
[GM_Handbook_-_EN.txt](https://github.com/NotThorny/AttackModifier/files/11728723/GM_Handbook_-_EN.txt)
