### ISSUE TITLE
为什么没有效果？

### ISSUE THREAD

**Issue by ChushaoLi** [NotThorny/AttackModifier#19]
我游戏是3.6版本。服务器插件加载正常，游戏里面没有效果。![image](https://github.com/NotThorny/AttackModifier/assets/117585936/26510c8b-d4d2-4489-8ff0-3c4619d63a14)

**Comment by ChushaoLi** [comment]
救命啊，弄了好多天没有任何效果。可以详细出一下教程吗？

**Comment by NotThorny** [comment]
Looks like you're using [AttackInfusedWithItem](https://github.com/snoobi-seggs/AttackInfusedWithItem) which is a variant of this plugin, but doesn't work quite the same and isn't updated with this. That version doesn't have on/off, so trying to use that won't work. Do note that effects are already enabled by default in both plugins though, so you don't need to use at on.

**Comment by ChushaoLi** [comment]
请问我应该用哪个游戏版本可以修改？> Looks like you're using [AttackInfusedWithItem](https://github.com/snoobi-seggs/AttackInfusedWithItem) which is a variant of this plugin, but doesn't work quite the same and isn't updated with this. That version doesn't have on/off, so trying to use that won't work. Do note that effects are already enabled by default in both plugins though, so you don't need to use at on.

**Comment by NotThorny** [comment]
[AttackModifier v1.3 release](https://github.com/NotThorny/AttackModifier/releases/tag/1.3) was made for game version 3.6 (Grasscutter 1.5.0) so you should try with that.

**Comment by ChushaoLi** [comment]
我的GC工具也需要1.5版本才可以的吗？

**Comment by NotThorny** [comment]
No, it should work with the version you already have. Just be sure you're selecting AttackModifier in there, not AttackInfusedWithItem.
