### ISSUE TITLE
can add option in +x +y +z

### ISSUE THREAD

**Issue by kamanya** [NotThorny/AttackModifier#21]
some boom spawn in character  ... boom~~
can add + pos x y z ?
example /at set n 70290344 x+123 y+30 z-110  ?
thanks

**Comment by NotThorny** [comment]
Here you go, but you have to understand that coordinates in the game are absolute, not relative. This means the gadget positions will change greatly based on what direction you are facing when you use it. Normally I add angle to make the gadget spawn in front of you, but with additional coordinate that won't work well so be aware.

The usage is `/at set n 70290344 x123 y123 z123` and you only have to include the x, y, or z that you want. Ex. `/at set n 70290344 y-15`

Open the zip and take out the jar from inside to use:
[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/12527968/AttackModifier.zip)

**Comment by kamanya** [comment]
Wow, great~~
Thank you very much
