### ISSUE TITLE
request for nahida

### ISSUE THREAD

**Issue by alyssio** [NotThorny/AttackModifier#3]
i want nahida to have her normal atks to shoot tighnaris burst arrows her e skill to shoot tighnaris e and her burst to be raining arrows if thats ok, dont go too extreme

**Comment by NotThorny** [comment]
Added functionality to specify gadgets on a per-avatar basis in 1409c4d
You can use this jar specifically for Nahida, but the burst is a vortex instead since I don't know the id for any raining arrows
[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/9781070/AttackModifier.zip)
