### ISSUE TITLE
为啥我放到文件夹里还是不能用

### ISSUE THREAD

**Issue by 3027Wudi** [NotThorny/AttackModifier#9]

**Comment by NotThorny** [comment]
![cmd_QrDW9UH4eq](https://user-images.githubusercontent.com/107363768/202524918-68a5b8ed-e663-498c-b0a0-45233b40bd13.png)

**Comment by 3027Wudi** [comment]
![MA4JV2GQ{M{ZPXLBTM}GLQJ](https://user-images.githubusercontent.com/118463117/202826151-0b5ab81a-aefd-4991-b03f-acffb522733e.png)
![_S}IR2F66DZ26P@1ZU%$ 06](https://user-images.githubusercontent.com/118463117/202826153-e3a2269c-1725-4408-82f8-98626298dca1.png)
我加载成功了但是游戏里打开的话会显示这个

**Comment by qingchunnh** [comment]
我跟你一样

**Comment by NotThorny** [comment]
This error is from AttackInfusedWithItem https://github.com/snoobi-seggs/AttackInfusedWithItem
